### PR TITLE
Add LAME audio conversion tool to FieldWorks dependencies for Linux

### PR DESCRIPTION
**Pull request by RaymondLuong3**
Signed-off-by: Raymond <raymond_luong@sil.org>

### CODE REVIEW

**Comment by JohnThomson** [comment]
I believe it was a deliberate decision NOT to ship LAME with Fieldworks, as with most of our programs, because of patent issues with MP3. Making it a full dependency will probably get it shipped.
That's probably OK..most sources seem to agree that the last MP3 patents in the US expired in April 2017, and elsewhere even earlier...but someone should probably give thought to whether we are ready to take the risk of shipping technology for making MP3s.

**Comment by RaymondLuong3** [comment]
Thanks for the information. I will look into this, and see if I can get that conversation started on shipping LAME and MP3 related technology.

**Comment by ermshiperete** [comment]
@RaymondLuong3, @JohnThomson Commits for `FwDebian` should be submitted to Gerrit (https://gerrit.lsdev.sil.org), not as GitHub PRs!

**Comment by ermshiperete** [comment]
@RaymondLuong3 Please re-submit this change on Gerrit (and on the `develop` branch).

**Comment by RaymondLuong3** [comment]
Sent from Mail for Windows 10

**Pull request merged**
